# Ansible managed
name: JAVA_CI
on:
  workflow_dispatch:
    branches: ['master']
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup requirements run
        run: sudo apt-get -qq -y install graphviz > /dev/null
      - name: Maven compile and update dependencies
        run: |
          ./mvnw -B -N io.takari:maven:wrapper
          ./mvnw -B -q versions:update-properties -DgenerateBackupPoms=false
          ./mvnw -B -q clean verify -Dmaven.test.skip=true
      - name: Run tests
        run: ./mvnw -B clean verify
      - name: Publish code quality
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
        with:
          coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
      - name: Tag and Push
        run: |
          wget -O github/scripts/versions.sh https://raw.githubusercontent.com/YunaBraska/YunaBraska/main/.github/scripts/versions.sh
          wget -O github/scripts/push_changes.sh https://raw.githubusercontent.com/YunaBraska/YunaBraska/main/.github/scripts/push_changes.sh
          wget -O github/scripts/increment_version.sh https://raw.githubusercontent.com/YunaBraska/YunaBraska/main/.github/scripts/increment_version.sh
          chmod +x github/scripts/versions.sh github/scripts/push_changes.sh github/scripts/increment_version.sh
          .github/scripts/push_changes.sh "https://x-access-token:${{ secrets.CI_TOKEN }}@github.com/${{ github.repository }}"
