# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: JAVA_CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup requirements
        run: sudo apt-get -qq -y install graphviz > /dev/null
      - name: Maven compile
        run: ./mvnw -B clean verify
      - name: Run tests
        run: ./mvnw -B clean verify
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          #        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          #        file: ./coverage.xml
          #        files: ./coverage1.xml,./coverage2.xml
          #        directory: ./coverage/reports/
          #        flags: unittests
          #        name: codecov-umbrella
          fail_ci_if_error: true
          #        path_to_write_report: ./coverage/codecov_report.txt
          verbose: false
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
        with:
          coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco





